excerpt_separator: ""
markdown: kramdown
highlighter: rouge
url: http://gavelph.github.io
title: Gavel PH
email: 
author: gavelph
description: My awesome new site
paginate: 10
google_analytics: 
